### ISSUE TITLE
Panic send on closed channel crash

### ISSUE THREAD

**Issue by robbyki** [moncho/dry#151]
Getting a crash when running against podman. Works on the rare occasion. Seems to be correctly pointing to the right socket. Installed this with go and also getting same result with `sh` install method. I'm on go 1.17.6 and a linux amd64 on a fedora 5.16 kernel.   

![image](https://user-images.githubusercontent.com/1027357/154521682-ec75087a-ac99-4379-b2d4-1a19b4ef64e6.png)

**Comment by linickx** [comment]
Still an issue (for me at least)

```
  Dry Version: 0.11.2
  Docker Host: unix:///var/run/docker.sock                                                                made with 💙 (and go) by moncho  panic: send on closed channel

                             goroutine 45 [running]:
                                                    github.com/moncho/dry/docker.(*DockerDaemon).Events.func1.streamEvents.1({0x103637300?, 0x14000092190?}, {{0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, {0x0, 0x0}, ...})
                                                                                /opt/code/go/dry/docker/events.go:17 +0x98
                                                                                                                          created by github.com/moncho/dry/docker.handleEvent in goroutine 40
                                                        /opt/code/go/dry/docker/events.go:41 +0x48

```

docker.sock is a symbolic link:

```
ls -l /var/run/docker.sock
lrwxr-xr-x@ - root 23 Aug 14:48 /var/run/docker.sock -> /Users/linickx/.local/share/containers/podman/machine/podman.sock
```

* Podman v5.2.1
* MacOS: 13.6.9
