### ISSUE TITLE
Invalid memory address or nil pointer dereference  on some Container

### ISSUE THREAD

**Issue by Vad1mo** [moncho/dry#64]
Just tried out the latest version and on Stats+Top I got:
```
panic: runtime error: invalid memory address or nil pointer dereference                                                ID:             4be8a0e849e5  Status:  Up 11 days                                                                
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0xa94826]
goroutine 114 [running]:
github.com/moncho/dry/appui.(*ContainerStatsRow).Update(0xc420086780, 0xc420319560, 0x0)
 IP Ad/opt/gocode/src/github.com/moncho/dry/appui/stats_row.go:148 +0x26  
github.com/moncho/dry/app.statsScreen(0xc420319560, 0xc42000a160, 0xc4203a25c0, 0xc420075500, 0xc4201dc010)
        /opt/gocode/src/github.com/moncho/dry/app/container_events.go:378 +0x3df      
created by github.com/moncho/dry/app.(*cMenuEventHandler).handleCommand              
        /opt/gocode/src/github.com/moncho/dry/app/cmenu_events.go:139 +0x650    
```

This repeatedly  happens on the Portianer Instance.  However not all containers are affected.

**Comment by moncho** [comment]
Fixed in release [v0.9-beta.5](https://github.com/moncho/dry/releases/tag/v0.9-beta.5).
