### ISSUE TITLE
Can't install dry using `brew install dry`

### ISSUE THREAD

**Issue by o6uoq** [moncho/dry#70]
brew was broken earlier and I identified it was dry. After manually removing dry and trying to re-install, the below error persists:
```
$ brew install dry
Error: uninitialized constant OS::NAME
Please report this bug:
  https://docs.brew.sh/Troubleshooting
/usr/local/Homebrew/Library/Taps/moncho/homebrew-dry/dry.rb:7:in `<class:Dry>'
/usr/local/Homebrew/Library/Taps/moncho/homebrew-dry/dry.rb:3:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `module_eval'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:26:in `load_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:46:in `load_formula_from_path'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:101:in `load_file'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:92:in `klass'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:88:in `get_formula'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:281:in `factory'
/usr/local/Homebrew/Library/Homebrew/formulary.rb:461:in `find_with_priority'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:48:in `block in formulae'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:44:in `map'
/usr/local/Homebrew/Library/Homebrew/extend/ARGV.rb:44:in `formulae'
/usr/local/Homebrew/Library/Homebrew/cmd/install.rb:118:in `install'
/usr/local/Homebrew/Library/Homebrew/brew.rb:99:in `<main>'
```
After this, I untapped `moncho/dry` and tried to re-install from scratching using:

`brew tap moncho/dry`
`brew install dry`

But this error broke on the tap:
```
$ brew tap moncho/dry
==> Tapping moncho/dry
Cloning into '/usr/local/Homebrew/Library/Taps/moncho/homebrew-dry'...
remote: Counting objects: 5, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 2 (delta 0), pack-reused 0
Unpacking objects: 100% (5/5), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/moncho/homebrew-dry/dry.rb
uninitialized constant OS::NAME
Error: Cannot tap moncho/dry: invalid syntax in tap!
```

**Comment by moncho** [comment]
Thanks for reporting the bug, @o6uoq!!

The Formula has been [fixed](https://github.com/moncho/homebrew-dry/commit/0e606c39933f7fbd1864d176ca547bae0f9c2301). Please let me know if you find any problem.

Cheers

**Comment by o6uoq** [comment]
No worries, thanks for the fast fix @moncho ! 👏🏼
