### ISSUE TITLE
crash going in and out of logs

### ISSUE THREAD

**Issue by thomasd3** [moncho/dry#83]
I had the following crash: "panic: runtime error: index out of range".

I couldn't reproduce it.
This is on Mac.

```
goroutine 39 [running]:
github.com/moncho/dry/appui.(*ContainersWidget).OnEvent(0xc0000ce2c0, 0xc0001f1540, 0x1532b40, 0x3)
	/opt/gocode/src/github.com/moncho/dry/appui/containers.go:146 +0xdd
github.com/moncho/dry/app.(*containersScreenEventHandler).handleKey(0xc00049caa0, 0xc0000b000d, 0xc00001c470, 0x0)
	/opt/gocode/src/github.com/moncho/dry/app/container_events.go:439 +0x41a
github.com/moncho/dry/app.(*containersScreenEventHandler).handle(0xc00049caa0, 0xd0000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc00001c470)
	/opt/gocode/src/github.com/moncho/dry/app/container_events.go:23 +0x46
github.com/moncho/dry/app.RenderLoop.func5(0xc0003b41e0, 0xc0000b9260)
	/opt/gocode/src/github.com/moncho/dry/app/loop.go:84 +0x118
created by github.com/moncho/dry/app.RenderLoop
	/opt/gocode/src/github.com/moncho/dry/app/loop.go:79 +0x260

```

you can see a screenshot here: https://imgur.com/a/xL7A6Gs

**Comment by moncho** [comment]
Fixed in [v0.9-beta.8](https://github.com/moncho/dry/releases/tag/v0.9-beta.8).
